// Generated by bonsai-flutter. Do not edit.
// ignore_for_file: avoid_relative_lib_imports

import '../lib/application_host_adapter.dart' as application;
import '../lib/main.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('managed host can be constructed', () {
    expect(
      BonsaiFlutterHost(adapter: application.createBonsaiFlutterHostAdapter()),
      isNotNull,
    );
  });
}
