(include_subdirs qualified)

(library
 (name logseq_db_worker_engine)
 (public_name logseq_db_worker.engine)
 (modules
  (:standard \ logseq_db_worker))
 (libraries
  datascript-ocaml-native
  datascript_ocaml
  digestif
  logseq_db_worker.contract
  logseq_db_storage
  logseq_db_types
  logseq_sync.pure_reducer
  melange-transit-native
  persistent_sorted_set_ocaml
  sqlite3
  unix
  uri
  uucp
  uunf
  uutf
  yojson)
 (flags
  (:standard
   -open
   Logseq_db_types
   -open
   Logseq_db_storage
   -open
   Logseq_db_worker_contract)))

(library
 (name logseq_db_worker)
 (public_name logseq_db_worker)
 (modules logseq_db_worker)
 (libraries
  eio
  logseq_db_worker.contract
  logseq_db_worker.effect_runner
  logseq_db_worker.engine
  logseq_db_worker.pure_reducer))
