opam-version: "2.0"
name: "logseq_journal"
version: "0.1.0"
synopsis: "Logseq Journal Bonsai Flutter application"
maintainer: "application authors"
authors: ["application authors"]
license: "MIT"
homepage: "https://github.com/RCmerci/logseq_journal"
bug-reports: "https://github.com/RCmerci/logseq_journal/issues"
depends: [
  "ocaml" {= "5.1.1"}
  "dune" {= "3.23.1"}
  "logseq_db_worker" {= "0.1.0"}
  "logseq_db_types" {= "0.1.0"}
  "logseq_sync" {= "0.1.0"}
  "bonsai_flutter" {= "0.1.0~dev"}
  "bonsai_flutter_test" {with-test & = "0.1.0~dev"}
  "base" {= "v0.17.3"}
  "bigstringaf" {= "0.10.0"}
  "bonsai" {= "v0.17.0"}
  "core" {= "v0.17.2"}
  "ca-certs-nss" {= "3.126"}
  "cstruct" {= "6.2.0"}
  "datascript_ocaml" {= "dev"}
  "datascript-ocaml-native" {= "dev"}
  "incr_dom" {= "v0.17.0"}
  "digestif" {= "1.3.1"}
  "domain-name" {= "0.5.0"}
  "eio" {= "1.2"}
  "faraday" {= "0.8.2"}
  "httpun" {= "0.2.0"}
  "httpun-eio" {= "0.2.0"}
  "httpun-ws" {= "0.2.0"}
  "melange-edn-core" {= "0.5.0"}
  "melange-edn-native" {= "0.5.0"}
  "melange-transit-core" {= "0.1.1"}
  "melange-transit-native" {= "0.1.1"}
  "persistent_sorted_set_ocaml" {= "dev"}
  "mirage-crypto-rng" {= "2.2.0"}
  "sqlite3" {= "5.4.0"}
  "tls" {= "2.1.2"}
  "tls-eio" {= "2.1.2"}
  "uri" {= "4.4.0"}
  "uucp" {= "17.0.0"}
  "uunf" {= "17.0.0"}
  "uutf" {= "1.0.4"}
  "virtual_dom" {= "v0.17.0"}
]
pin-depends: [
  ["bonsai_flutter.0.1.0~dev" "git+https://github.com/RCmerci/bonsai_flutter.git#de1196c2663b43388ebf04bd0612c5050edef753"]
  ["bonsai_flutter_test.0.1.0~dev" "git+https://github.com/RCmerci/bonsai_flutter.git#de1196c2663b43388ebf04bd0612c5050edef753"]
  ["datascript_ocaml.dev" "git+https://github.com/logseq/datascript-ocaml.git#5895af25101de15f56d7c5df383c150ca07cef90"]
  ["datascript-ocaml-native.dev" "git+https://github.com/logseq/datascript-ocaml.git#5895af25101de15f56d7c5df383c150ca07cef90"]
  ["persistent_sorted_set_ocaml.dev" "git+https://github.com/logseq/persistent-sorted-set-ocaml.git#4016dae1cdf4304207d8277ff9957656cdd8b177"]
  ["melange-edn-core.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-edn-native.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-transit-core.0.1.1" "git+https://github.com/RCmerci/melange-transit.git#a64270a1ed5c8ad3ff7e05dbb60e83ad0465ae93"]
  ["melange-transit-native.0.1.1" "git+https://github.com/RCmerci/melange-transit.git#a64270a1ed5c8ad3ff7e05dbb60e83ad0465ae93"]
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
