opam-version: "2.0"
name: "logseq_journal"
version: "0.1.0"
synopsis: "Logseq Journal LUI application"
maintainer: "application authors"
authors: ["application authors"]
license: "MIT"
homepage: "https://github.com/logseq/logseq_journal"
bug-reports: "https://github.com/logseq/logseq_journal/issues"
depends: [
  "rrbvec" {= "dev"}
  "ocaml" {>= "5.4"}
  "dune" {= "3.23.1"}
  "logseq_db_worker" {= "0.1.0"}
  "logseq_db_types" {= "0.1.0"}
  "logseq_sync" {= "0.1.0"}
  "lui" {= "0.1.0"}
  "ocaml-signal" {= "0.1.0"}
  "base" {= "v0.17.3"}
  "bigstringaf" {= "0.10.0"}
  "core" {= "v0.17.2"}
  "ca-certs-nss" {= "3.126"}
  "cstruct" {= "6.2.0"}
  "datascript_ocaml" {= "dev"}
  "datascript-ocaml-native" {= "dev"}
  "digestif" {= "1.3.1"}
  "domain-name" {= "0.5.0"}
  "eio" {= "1.2"}
  "faraday" {= "0.8.2"}
  "httpun" {= "0.2.0"}
  "httpun-eio" {= "0.2.0"}
  "httpun-ws" {= "0.2.0"}
  "melange-edn-core" {= "0.5.0"}
  "melange-edn-native" {= "0.5.0"}
  "melange-transit-core" {= "0.1.2"}
  "melange-transit-native" {= "0.1.2"}
  "persistent_sorted_set_ocaml" {= "dev"}
  "mirage-crypto-rng" {= "2.2.0"}
  "sqlite3" {= "5.4.0"}
  "tls" {= "2.1.2"}
  "tls-eio" {= "2.1.2"}
  "uri" {= "4.4.0"}
  "uucp" {= "17.0.0"}
  "uunf" {= "17.0.0"}
  "uutf" {= "1.0.4"}
]
pin-depends: [
  ["rrbvec.dev" "git+https://github.com/logseq/rrbvec.git#main"]
  ["lui.0.1.0" "git+https://github.com/logseq/lui.git#473b6c6a81fc2ce9e9dbe9116abca14ef2ac2c25"]
  ["ocaml-signal.0.1.0" "git+https://github.com/logseq/ocaml-signal.git#976b40f1770a65b3464df1ef38d1550f1d8a43dd"]
  ["datascript_ocaml.dev" "git+https://github.com/logseq/datascript-ocaml.git#40345cc2f59214daa88b33b8aec711337d20afa7"]
  ["datascript-ocaml-native.dev" "git+https://github.com/logseq/datascript-ocaml.git#40345cc2f59214daa88b33b8aec711337d20afa7"]
  ["persistent_sorted_set_ocaml.dev" "git+https://github.com/logseq/persistent-sorted-set-ocaml.git#4016dae1cdf4304207d8277ff9957656cdd8b177"]
  ["melange-edn-core.0.5.0" "git+https://github.com/logseq/melange-edn.git#main"]
  ["melange-edn-native.0.5.0" "git+https://github.com/logseq/melange-edn.git#main"]
  ["melange-transit-core.0.1.2" "git+https://github.com/logseq/melange-transit.git#35f8afe7d6506863c7253e67a20befb3dde5c18f"]
  ["melange-transit-native.0.1.2" "git+https://github.com/logseq/melange-transit.git#35f8afe7d6506863c7253e67a20befb3dde5c18f"]
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
