opam-version: "2.0"
name: "logseq_db_storage"
version: "0.1.0"
synopsis: "Logseq DataScript and SQLite storage"
maintainer: "application authors"
authors: ["application authors"]
license: "MIT"
homepage: "https://github.com/RCmerci/logseq_journal"
bug-reports: "https://github.com/RCmerci/logseq_journal/issues"
depends: [
  "ocaml" {= "5.1.1"}
  "dune" {= "3.23.1"}
  "logseq_db_types" {= "0.1.0"}
  "datascript_ocaml" {= "dev"}
  "datascript-ocaml-native" {= "dev"}
  "melange-transit-native" {= "0.1.0"}
  "persistent_sorted_set_ocaml" {= "dev"}
  "sqlite3" {= "5.4.0"}
  "yojson" {= "3.0.0"}
]
pin-depends: [
  ["datascript_ocaml.dev" "git+https://github.com/logseq/datascript-ocaml.git#b1029d6a7210baae15aa2189293bd126b746bad4"]
  ["datascript-ocaml-native.dev" "git+https://github.com/logseq/datascript-ocaml.git#b1029d6a7210baae15aa2189293bd126b746bad4"]
  ["melange-transit-native.0.1.0" "git+https://github.com/RCmerci/melange-transit.git#b298260eb67d96710cb26eaad96a40c81b1af21b"]
  ["persistent_sorted_set_ocaml.dev" "git+https://github.com/logseq/persistent-sorted-set-ocaml.git#4016dae1cdf4304207d8277ff9957656cdd8b177"]
]
build: [["dune" "build" "-p" name "-j" jobs]]
