opam-version: "2.0"
name: "logseq_db_worker"
version: "0.1.0"
synopsis: "Logseq DB graph worker for OCaml"
maintainer: "application authors"
authors: ["application authors"]
license: "MIT"
homepage: "https://github.com/RCmerci/logseq_journal"
bug-reports: "https://github.com/RCmerci/logseq_journal/issues"
depends: [
  "ocaml" {= "5.1.1"}
  "dune" {= "3.23.1"}
  "logseq_db_types" {= "0.1.0"}
  "logseq_overlay_db" {= "0.1.0"}
  "logseq_sync" {= "0.1.0"}
  "base" {= "v0.17.3"}
  "bonsai" {= "v0.17.0"}
  "bonsai_flutter" {= "0.1.0~dev"}
  "bonsai_flutter_test" {with-test & = "0.1.0~dev"}
  "core" {= "v0.17.2"}
  "eio" {= "1.2"}
  "mtime" {= "2.1.0"}
  "melange-transit-native" {= "0.1.2"}
  "uri" {= "4.4.0"}
  "yojson" {= "3.0.0"}
]
pin-depends: [
  ["datascript_ocaml.dev" "git+https://github.com/logseq/datascript-ocaml.git#40345cc2f59214daa88b33b8aec711337d20afa7"]
  ["datascript-ocaml-native.dev" "git+https://github.com/logseq/datascript-ocaml.git#40345cc2f59214daa88b33b8aec711337d20afa7"]
  ["melange-edn-core.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-edn-native.0.5.0" "git+https://github.com/RCmerci/melange-edn.git#3cb79f278e972388a0a2b2ea1caec7a008a0b956"]
  ["melange-transit-core.0.1.2" "git+https://github.com/RCmerci/melange-transit.git#35f8afe7d6506863c7253e67a20befb3dde5c18f"]
  ["melange-transit-native.0.1.2" "git+https://github.com/RCmerci/melange-transit.git#35f8afe7d6506863c7253e67a20befb3dde5c18f"]
  ["bonsai_flutter.0.1.0~dev" "git+https://github.com/RCmerci/bonsai_flutter.git#3d2a540d886839fb243ce78f4bcc38da13c600a9"]
  ["bonsai_flutter_test.0.1.0~dev" "git+https://github.com/RCmerci/bonsai_flutter.git#3d2a540d886839fb243ce78f4bcc38da13c600a9"]
]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
