// Generated by bonsai-flutter. Do not edit.
import 'dart:typed_data';

import 'package:bonsai_flutter/bonsai_flutter.dart';
import 'package:flutter/material.dart';

import 'application_host_adapter.dart' as application;

void main() {
  final adapter = application.createBonsaiFlutterHostAdapter();
  runApp(BonsaiFlutterHost(adapter: adapter));
}

final class BonsaiFlutterHost extends StatefulWidget {
  const BonsaiFlutterHost({required this.adapter, super.key});

  final BonsaiFlutterHostAdapter adapter;

  @override
  State<BonsaiFlutterHost> createState() => _BonsaiFlutterHostState();
}

final class _PreparedRuntime {
  const _PreparedRuntime({
    required this.runtimeConfig,
    required this.applicationPlatform,
  });

  final Uint8List runtimeConfig;
  final BonsaiFlutterApplicationPlatform? applicationPlatform;
}

final class _BonsaiFlutterHostState extends State<BonsaiFlutterHost> {
  late Future<_PreparedRuntime> _preparedRuntime;

  @override
  void initState() {
    super.initState();
    _preparedRuntime = _prepareRuntime();
  }

  @override
  void didUpdateWidget(covariant BonsaiFlutterHost oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!identical(widget.adapter, oldWidget.adapter)) {
      _preparedRuntime = _prepareRuntime();
    }
  }

  Future<_PreparedRuntime> _prepareRuntime() async {
    final applicationPayload = await widget.adapter.createApplicationPayload();
    final applicationPlatform = widget.adapter.createApplicationPlatform();
    return _PreparedRuntime(
      runtimeConfig: RuntimeBootstrapConfig(
        entrypoint: 'logseq_journal',
        launchPolicy: RuntimeLaunchPolicy.replaceExisting,
        applicationPayload: applicationPayload,
      ).encode(),
      applicationPlatform: applicationPlatform,
    );
  }

  @override
  Widget build(BuildContext context) => FutureBuilder<_PreparedRuntime>(
    future: _preparedRuntime,
    builder: (context, snapshot) {
      final prepared = snapshot.data;
      final Widget home;
      if (snapshot.error case final error?) {
        home = Center(child: Text('Unable to prepare application: $error'));
      } else if (prepared == null) {
        home = const Center(child: CircularProgressIndicator());
      } else {
        home = BonsaiFlutterRoot(
          config: prepared.runtimeConfig,
          applicationPlatform: prepared.applicationPlatform,
        );
      }
      return widget.adapter.buildHost(
        context: context,
        child: MaterialApp(title: 'logseq_journal', home: home),
      );
    },
  );
}
