(library
 (name logseq_db_worker_bonsai)
 (public_name logseq_db_worker.bonsai)
 (libraries
  bonsai_flutter.driver
  eio
  logseq_db_worker
  logseq_db_storage
  logseq_db_types
  logseq_sync.effect_runner
  logseq_sync.pure_reducer
  melange-transit-native
  mtime.clock.os
  unix
  uri
  yojson))
