(include_subdirs unqualified)

(library
 (name logseq_sync_effect_runner_impl)
 (public_name logseq_sync.effect_runner.impl)
 (implements logseq_sync_effect_runner)
 (modules
  artifact_decoder
  bootstrap
  catalog
  e2ee
  effect_runner
  http
  http_eio
  platform_crypto
  tls_client_eio
  websocket_eio)
 (private_modules
  artifact_decoder
  bootstrap
  catalog
  e2ee
  http
  http_eio
  platform_crypto
  tls_client_eio
  websocket_eio)
 (libraries
  bigstringaf
  ca-certs-nss
  cstruct
  digestif
  domain-name
  eio
  eio.unix
  faraday
  httpun
  httpun-eio
  httpun-ws
  logseq_overlay_db
  logseq_sync.pure_reducer
  logseq_db_types
  melange-transit-native
  mirage-crypto-rng
  mirage-crypto-rng.unix
  tls-eio
  unix
  uri
  yojson)
 (flags
  (:standard -open Logseq_db_types))
 (foreign_stubs
  (language c)
  (names platform_crypto_stubs gzip_stubs)))
